"""
tools.py
========
Four ADK tools for the AGCM Estimation Agent.
Loads real project data from projects.json and divisions.json
generated by setup_data.py.

Tools:
  1. validate_project_inputs      — checks what info was provided, decides if estimate is possible
  2. find_similar_projects        — finds past AGCM projects using weighted similarity scoring
  3. get_division_benchmarks      — returns $/SF by CSI division benchmarked to comparable projects
  4. calculate_estimate_total     — computes price, margin, category, schedule from benchmarks
"""

import os
import json
import math
from typing import Optional

# ─── DATA LOADING ──────────────────────────────────────────────────────────────

_DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

def _load_projects() -> list[dict]:
    path = os.path.join(_DATA_DIR, "projects.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def _load_divisions() -> list[dict]:
    path = os.path.join(_DATA_DIR, "divisions.json")
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

# Load once at module import
_PROJECTS = _load_projects()
_DIVISIONS = _load_divisions()

# ─── PROJECT TYPE ALIASES ───────────────────────────────────────────────────────
# Maps user input keywords → canonical project_type values in our data

_TYPE_ALIASES: dict[str, str] = {
    # Multi-Res / Institutional
    "multi-res": "Multi-Residential / Institutional",
    "multi res": "Multi-Residential / Institutional",
    "multires": "Multi-Residential / Institutional",
    "multi-residential": "Multi-Residential / Institutional",
    "residential": "Multi-Residential / Institutional",
    "apartment": "Multi-Residential / Institutional",
    "condo": "Multi-Residential / Institutional",
    "ymca": "Multi-Residential / Institutional",
    "daycare": "Multi-Residential / Institutional",
    "school": "Multi-Residential / Institutional",
    "institutional": "Multi-Residential / Institutional",
    "community": "Multi-Residential / Institutional",
    # Medical / Dental
    "dental": "Medical / Dental",
    "medical": "Medical / Dental",
    "clinic": "Medical / Dental",
    "wellness": "Medical / Dental",
    "health": "Medical / Dental",
    "pharmacy": "Medical / Dental",
    "doctor": "Medical / Dental",
    # Grocery / Food Retail
    "grocery": "Grocery / Food Retail",
    "sobeys": "Grocery / Food Retail",
    "supermarket": "Grocery / Food Retail",
    "food": "Grocery / Food Retail",
    "foodland": "Grocery / Food Retail",
    "atlanticsuperstore": "Grocery / Food Retail",
    # Automotive
    "automotive": "Automotive",
    "auto": "Automotive",
    "ford": "Automotive",
    "dealership": "Automotive",
    "car": "Automotive",
    "vehicle": "Automotive",
    # Renovation / Tenant Fit-up
    "renovation": "Renovation / Tenant Fit-up",
    "reno": "Renovation / Tenant Fit-up",
    "fit-up": "Renovation / Tenant Fit-up",
    "fit up": "Renovation / Tenant Fit-up",
    "tenant": "Renovation / Tenant Fit-up",
    "fitout": "Renovation / Tenant Fit-up",
    "expansion": "Renovation / Tenant Fit-up",
    "retrofit": "Renovation / Tenant Fit-up",
    # Commercial / Other
    "office": "Commercial / Other",
    "commercial": "Commercial / Other",
    "retail": "Commercial / Other",
    "warehouse": "Commercial / Other",
    "industrial": "Commercial / Other",
    "mixed": "Commercial / Other",
}

def _normalize_type(raw: str) -> Optional[str]:
    """Map a free-text project type to a canonical type."""
    if not raw:
        return None
    key = raw.lower().strip().replace("-", " ")
    for alias, canonical in _TYPE_ALIASES.items():
        if alias in key:
            return canonical
    # If no alias matches, return as-is (agent will handle unknowns)
    return raw.strip()

# ─── PRICE CATEGORY LOGIC ──────────────────────────────────────────────────────

def _price_category(price: float) -> tuple[str, float]:
    """
    Returns (category_label, suggested_margin) based on AGCM's pricing tiers.
    A >$5M  → ~10% margin
    B $2-5M → ~15% margin
    C $500K-2M → ~20% margin
    D <$500K → ~25% margin
    """
    if price >= 5_000_000:
        return "A (>$5M)", 0.10
    elif price >= 2_000_000:
        return "B ($2M–$5M)", 0.15
    elif price >= 500_000:
        return "C ($500K–$2M)", 0.20
    else:
        return "D (<$500K)", 0.25

# ─── SIMILARITY SCORING ────────────────────────────────────────────────────────

def _similarity_score(project: dict, project_type: str, area_sf: float,
                       province: str, city: str) -> float:
    """
    Weighted similarity score (0–100) between a past project and the query.

    Weights:
      - Project type match  : 40 pts  (most important — drives division mix)
      - Area similarity      : 30 pts  (log-scale, ±50% = full score)
      - Province match       : 15 pts
      - City match           : 10 pts
      - Recency (year)       : 5 pts   (newer = slightly preferred)
    """
    score = 0.0

    # 1. Project type (40 pts)
    canonical = _normalize_type(project_type) or ""
    if project["project_type"] == canonical:
        score += 40
    elif _partial_type_match(project["project_type"], canonical):
        score += 20

    # 2. Area similarity (30 pts) — log-scale so 10K SF vs 12K SF isn't penalized harshly
    if area_sf and project["area_sf"]:
        ratio = area_sf / project["area_sf"]
        # log ratio = 0 when identical, grows as they diverge
        log_diff = abs(math.log(ratio))
        # Full 30 pts if within ~10%, decays to 0 at ~5x difference
        area_score = max(0.0, 30 * (1 - log_diff / math.log(5)))
        score += area_score

    # 3. Province (15 pts)
    if province and project["province"]:
        if project["province"].upper() == province.upper():
            score += 15

    # 4. City (10 pts)
    if city and project["city"]:
        if project["city"].lower() == city.lower():
            score += 10
        elif city.lower() in project["city"].lower() or project["city"].lower() in city.lower():
            score += 5

    # 5. Recency (5 pts) — 2026 = 5 pts, each year back = -1 pt
    year = project.get("budget_year") or 2020
    recency = max(0, 5 - (2026 - int(year)))
    score += recency

    return round(score, 1)


def _partial_type_match(type_a: str, type_b: str) -> bool:
    """Check if two project types share a broad category."""
    broad = [
        {"Multi-Residential / Institutional"},
        {"Medical / Dental", "Commercial / Other"},
        {"Grocery / Food Retail", "Retail"},
        {"Automotive"},
        {"Renovation / Tenant Fit-up"},
    ]
    for group in broad:
        if type_a in group and type_b in group:
            return True
    return False


# ══════════════════════════════════════════════════════════════════════════════
# TOOL 1 — validate_project_inputs
# ══════════════════════════════════════════════════════════════════════════════

def validate_project_inputs(
    project_type: str,
    area_sf: Optional[float] = None,
    province: Optional[str] = None,
    city: Optional[str] = None,
    contract_type: Optional[str] = None,
) -> dict:
    """
    Validates the project inputs provided by the user.
    Returns which fields are present, which are missing, and whether
    we have enough to generate a useful estimate.

    Args:
        project_type:  Type of construction (e.g. "Multi-Residential", "Dental Office")
        area_sf:       Total area in square feet
        province:      Canadian province abbreviation (e.g. "NB", "NS")
        city:          City or town name
        contract_type: Contract type (e.g. "CCDC 5B", "Fixed Fee", "Design Build")

    Returns:
        dict with: fields_provided, fields_missing, can_estimate, canonical_type, warnings
    """
    fields_provided = []
    fields_missing = []
    warnings = []

    # Project type
    canonical_type = None
    if project_type:
        canonical_type = _normalize_type(project_type)
        fields_provided.append("project_type")
        if canonical_type == project_type.strip() and project_type.strip() not in _TYPE_ALIASES:
            warnings.append(
                f"Project type '{project_type}' is not a recognized AGCM category. "
                f"Will attempt to find closest match. Known types: "
                f"Multi-Residential, Medical/Dental, Grocery, Automotive, Renovation/Tenant Fit-up, Commercial."
            )
    else:
        fields_missing.append("project_type")

    # Area
    if area_sf and area_sf > 0:
        fields_provided.append("area_sf")
        if area_sf < 500:
            warnings.append(f"Area of {area_sf:,.0f} SF is very small — estimate confidence will be low.")
        elif area_sf > 200_000:
            warnings.append(f"Area of {area_sf:,.0f} SF is larger than any project in the AGCM database — comparables will be extrapolated.")
    else:
        fields_missing.append("area_sf")

    # Province
    if province:
        fields_provided.append("province")
        if province.upper() not in ["NB", "NS", "PEI", "NL", "PE"]:
            warnings.append(f"Province '{province}' is outside Atlantic Canada — no direct comparables, will use NB benchmarks.")
    else:
        fields_missing.append("province")
        warnings.append("Province not provided — defaulting to NB benchmarks.")

    # City (optional but helpful)
    if city:
        fields_provided.append("city")
    else:
        fields_missing.append("city")

    # Contract type (optional)
    if contract_type:
        fields_provided.append("contract_type")
    else:
        fields_missing.append("contract_type")

    # Decision: can we estimate?
    # Minimum needed: project_type + area_sf
    can_estimate = "project_type" in fields_provided and "area_sf" in fields_provided

    return {
        "fields_provided": fields_provided,
        "fields_missing": fields_missing,
        "can_estimate": can_estimate,
        "canonical_type": canonical_type,
        "warnings": warnings,
        "message": (
            "Sufficient information to generate an estimate."
            if can_estimate
            else f"Cannot estimate yet. Required fields missing: {', '.join(fields_missing)}. "
                 f"Please ask the user for: {' and '.join(fields_missing)}."
        ),
    }


# ══════════════════════════════════════════════════════════════════════════════
# TOOL 2 — find_similar_projects
# ══════════════════════════════════════════════════════════════════════════════

def find_similar_projects(
    project_type: str,
    area_sf: float,
    province: str = "NB",
    city: str = "",
    top_n: int = 3,
) -> dict:
    """
    Finds the most similar past AGCM projects using weighted scoring.
    Returns top N matches with similarity scores and key benchmarks.

    Args:
        project_type: Type of construction (canonical or free-text)
        area_sf:      Total project area in square feet
        province:     Province abbreviation (default "NB")
        city:         City name (optional, improves matching)
        top_n:        Number of results to return (default 3)

    Returns:
        dict with: matches (list), coverage_warning, avg_cost_per_sf
    """
    scored = []
    for p in _PROJECTS:
        score = _similarity_score(p, project_type, area_sf, province, city)
        scored.append((score, p))

    # Sort descending by score
    scored.sort(key=lambda x: x[0], reverse=True)
    top = scored[:top_n]

    matches = []
    for score, p in top:
        # Size ratio for context
        size_ratio = area_sf / p["area_sf"] if p["area_sf"] else 1.0
        size_diff_pct = round((size_ratio - 1) * 100, 1)

        matches.append({
            "estimate_number":  p["estimate_number"],
            "estimate_name":    p["estimate_name"],
            "project_type":     p["project_type"],
            "area_sf":          p["area_sf"],
            "area_diff_pct":    size_diff_pct,    # +ve = new project is larger
            "province":         p["province"],
            "city":             p["city"],
            "budget_year":      p["budget_year"],
            "estimate_price":   p["estimate_price"],
            "cost_per_sf":      p["cost_per_sf"],
            "margin_pct":       p["margin_pct"],
            "schedule_weeks":   p["schedule_weeks"],
            "contract_type":    p["contract_type"],
            "result":           p["result"],
            "similarity_score": score,
            "confidence":       _confidence_label(score),
        })

    # Aggregate avg $/SF from top matches (weighted by similarity score)
    total_weight = sum(s for s, _ in top)
    if total_weight > 0:
        avg_cost_per_sf = sum(
            s * p["cost_per_sf"] for s, p in top
        ) / total_weight
    else:
        avg_cost_per_sf = 0

    # Coverage warning if best score is low
    best_score = top[0][0] if top else 0
    coverage_warning = None
    if best_score < 30:
        coverage_warning = (
            f"Best match score is only {best_score}/100 — "
            f"no strong comparable exists in the AGCM database for this project type/size. "
            f"Estimate confidence is LOW. Consider using general Atlantic Canada benchmarks."
        )
    elif best_score < 55:
        coverage_warning = (
            f"Moderate match quality (score {best_score}/100). "
            f"Comparable projects differ in type or size. Treat as indicative only."
        )

    return {
        "matches": matches,
        "total_projects_in_database": len(_PROJECTS),
        "avg_cost_per_sf_weighted": round(avg_cost_per_sf, 2),
        "coverage_warning": coverage_warning,
        "query": {
            "project_type": _normalize_type(project_type),
            "area_sf": area_sf,
            "province": province,
            "city": city,
        },
    }


def _confidence_label(score: float) -> str:
    if score >= 70:
        return "HIGH"
    elif score >= 45:
        return "MEDIUM"
    elif score >= 25:
        return "LOW"
    else:
        return "VERY LOW"


# ══════════════════════════════════════════════════════════════════════════════
# TOOL 3 — get_division_benchmarks
# ══════════════════════════════════════════════════════════════════════════════

def get_division_benchmarks(
    project_type: str,
    area_sf: float,
    province: str = "NB",
    comparable_estimate_numbers: Optional[list[str]] = None,
) -> dict:
    """
    Returns CSI division-level $/SF benchmarks for the new project,
    derived from the most similar past projects.

    If comparable_estimate_numbers are provided (from find_similar_projects),
    uses those projects' exact division data. Otherwise finds the best matches.

    Args:
        project_type:                  Type of construction
        area_sf:                       New project area in SF
        province:                      Province
        comparable_estimate_numbers:   List of estimate numbers to use as source (optional)

    Returns:
        dict with: divisions (list of CSI benchmarks), total_construction_cost, total_cost_per_sf
    """
    # Determine which projects to pull division data from
    if comparable_estimate_numbers:
        source_nums = set(comparable_estimate_numbers)
        source_divs = [d for d in _DIVISIONS if d["estimate_number"] in source_nums]
    else:
        # Find top 3 similar projects
        result = find_similar_projects(project_type, area_sf, province, top_n=3)
        source_nums = set(m["estimate_number"] for m in result["matches"])
        source_divs = [d for d in _DIVISIONS if d["estimate_number"] in source_nums]

    if not source_divs:
        return {
            "error": "No division data found for the selected comparable projects.",
            "divisions": [],
            "total_construction_cost": 0,
            "total_cost_per_sf": 0,
        }

    # Group by division code, compute weighted average $/SF
    from collections import defaultdict
    division_groups: dict[str, list] = defaultdict(list)
    for d in source_divs:
        division_groups[d["division_code"]].append(d)

    benchmarks = []
    total_cost_per_sf = 0.0

    for code in sorted(division_groups.keys()):
        entries = division_groups[code]
        div_name = entries[0]["division_name"]

        # Weighted average $/SF — weight by how similar area is to new project
        weights = []
        for e in entries:
            if e["area_sf"] and e["area_sf"] > 0:
                ratio = area_sf / e["area_sf"]
                w = 1 / (1 + abs(math.log(ratio)))  # closer = higher weight
            else:
                w = 0.5
            weights.append(w)

        total_w = sum(weights)
        if total_w > 0:
            avg_cost_per_sf = sum(
                e["cost_per_sf"] * w for e, w in zip(entries, weights)
            ) / total_w
            avg_pct = sum(
                e["pct_of_project"] * w for e, w in zip(entries, weights)
            ) / total_w
        else:
            avg_cost_per_sf = 0
            avg_pct = 0

        estimated_total = round(avg_cost_per_sf * area_sf, 2)

        # Min/max range across comparables for confidence bounds
        cpf_values = [e["cost_per_sf"] for e in entries if e["cost_per_sf"] > 0]
        range_low  = min(cpf_values) if cpf_values else 0
        range_high = max(cpf_values) if cpf_values else 0

        benchmarks.append({
            "division_code":        code,
            "division_name":        div_name,
            "cost_per_sf":          round(avg_cost_per_sf, 2),
            "estimated_total":      estimated_total,
            "pct_of_project":       round(avg_pct, 2),
            "range_low_per_sf":     round(range_low, 2),
            "range_high_per_sf":    round(range_high, 2),
            "source_project_count": len(entries),
            "comparable_projects":  [e["estimate_name"] for e in entries],
        })

        total_cost_per_sf += avg_cost_per_sf

    total_construction_cost = round(total_cost_per_sf * area_sf, 2)

    return {
        "divisions":                benchmarks,
        "total_construction_cost":  total_construction_cost,
        "total_cost_per_sf":        round(total_cost_per_sf, 2),
        "area_sf":                  area_sf,
        "source_projects":          list(source_nums),
        "division_count":           len(benchmarks),
    }


# ══════════════════════════════════════════════════════════════════════════════
# TOOL 4 — calculate_estimate_total
# ══════════════════════════════════════════════════════════════════════════════

def calculate_estimate_total(
    construction_cost: float,
    area_sf: float,
    ohp_pct: Optional[float] = None,
    soft_cost: Optional[float] = None,
    override_margin_pct: Optional[float] = None,
) -> dict:
    """
    Calculates the final estimate price, margin, price category, and schedule
    from the construction cost subtotal.

    Applies AGCM's standard OH&P and margin logic based on project size category.

    Args:
        construction_cost:   Raw construction cost (from get_division_benchmarks)
        area_sf:             Total area in SF
        ohp_pct:             OH&P percentage to apply (default: 5% per AGCM standard)
        soft_cost:           Soft costs to add (default: 5% of construction cost)
        override_margin_pct: Override the auto-suggested margin

    Returns:
        dict with: estimate_price, margin_pct, price_category, cost_per_sf,
                   schedule_weeks, ohp, soft_cost, breakdown
    """
    # Defaults
    ohp_pct_applied    = ohp_pct if ohp_pct is not None else 5.0
    soft_cost_applied  = soft_cost if soft_cost is not None else round(construction_cost * 0.05, 2)

    # OH&P
    ohp_amount = round(construction_cost * (ohp_pct_applied / 100), 2)

    # Subtotal before margin
    subtotal = construction_cost + ohp_amount + soft_cost_applied

    # Determine price category + suggested margin
    # Estimate price ≈ subtotal / (1 - margin)
    # First pass with 10% margin to get category
    first_pass_price = subtotal / (1 - 0.10)
    category_label, suggested_margin = _price_category(first_pass_price)

    # Use override if provided
    margin_pct = override_margin_pct if override_margin_pct is not None else suggested_margin * 100

    # Final price
    estimate_price = round(subtotal / (1 - margin_pct / 100), 2)

    # Recalculate category with real price
    category_label, _ = _price_category(estimate_price)

    cost_per_sf = round(estimate_price / area_sf, 2) if area_sf else 0

    # Schedule estimate: ~$12,000–$15,000 per week for NB construction (from AGCM data)
    # Interpolate based on project size
    avg_cost_per_week = 12000 if estimate_price < 2_000_000 else 13500
    schedule_weeks = max(4, round(estimate_price / avg_cost_per_week))

    return {
        "estimate_price":        estimate_price,
        "margin_pct":            margin_pct,
        "price_category":        category_label,
        "cost_per_sf":           cost_per_sf,
        "schedule_weeks":        schedule_weeks,
        "breakdown": {
            "construction_cost": construction_cost,
            "ohp_pct":           ohp_pct_applied,
            "ohp_amount":        ohp_amount,
            "soft_cost":         soft_cost_applied,
            "subtotal":          subtotal,
            "margin_pct":        margin_pct,
            "final_price":       estimate_price,
        },
        "notes": [
            f"Price category: {category_label} — AGCM standard margin for this range is {suggested_margin*100:.0f}%.",
            f"Schedule of {schedule_weeks} weeks is an estimate based on AGCM's historical cost-per-week ratio.",
            "Soft costs ({:.1f}% of construction) cover design, permits, surveys.".format(
                soft_cost_applied / construction_cost * 100 if construction_cost else 0
            ),
        ],
    }


# ─── QUICK SELF-TEST ────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=== Tool Self-Test ===\n")

    print("1. validate_project_inputs()")
    v = validate_project_inputs("dental office", 2000, "NB", "Moncton")
    print(json.dumps(v, indent=2))

    print("\n2. find_similar_projects()")
    s = find_similar_projects("dental", 2000, "NB", "Moncton")
    for m in s["matches"]:
        print(f"   [{m['similarity_score']:5.1f}] {m['estimate_name']} "
              f"({m['area_sf']:,.0f} SF, {m['margin_pct']}% margin, {m['confidence']})")

    print("\n3. get_division_benchmarks()")
    b = get_division_benchmarks("dental", 2000, "NB")
    print(f"   Total $/SF: ${b['total_cost_per_sf']:.2f}")
    print(f"   Total construction cost: ${b['total_construction_cost']:,.0f}")
    for d in b["divisions"]:
        if d["cost_per_sf"] > 0:
            print(f"   {d['division_code']} {d['division_name'][:30]:<30} "
                  f"${d['cost_per_sf']:>6.2f}/SF  ${d['estimated_total']:>10,.0f}")

    print("\n4. calculate_estimate_total()")
    c = calculate_estimate_total(b["total_construction_cost"], 2000)
    print(f"   Estimate price  : ${c['estimate_price']:,.0f}")
    print(f"   Price category  : {c['price_category']}")
    print(f"   Margin          : {c['margin_pct']}%")
    print(f"   Cost per SF     : ${c['cost_per_sf']:.2f}")
    print(f"   Schedule        : {c['schedule_weeks']} weeks")